import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Printer, ArrowLeft, RefreshCw, AlertCircle } from 'lucide-react';
import taskService from '../services/taskService';
import sprintService from '../services/sprintService';
import slaService from '../services/slaService';
import useAuthStore from '../store/authStore';
import api from '../services/api';
import { useLanguage } from '../i18n/LanguageContext';
import { translateBatch } from '../i18n/translateService';
import { useTheme } from '../contexts/ThemeContext';

// ── Report content strings (translated per report language) ──────────────────
const REPORT_STRINGS = {
  page_label:    'Page',
  footer:        'Attijari Bank IT Department - PriorIT Report - Confidential',
  ai_badge:      'AI Generated',
  it_dept:       'IT Department',
  bank:          'Attijari Bank Tunisia',
  gen_by:        'Generated by',
  confidential:  'Confidential - Internal Use Only',
  version:       'PriorIT v1.0',
  c_tasks:       'Total Tasks',
  c_ai:          'AI Scored',
  c_sprint:      'Sprint Progress',
  c_sla:         'SLA Compliance',
  c_team:        'Team Members',
  s1:            'Section 1',
  s1_title:      'Executive Summary',
  s2:            'Section 2',
  s2_title:      'Task Priority Ranking',
  s3:            'Section 3',
  s3_title:      'Active Sprint Status',
  s4:            'Section 4',
  s4_title:      'SLA and Delivery Compliance',
  s5:            'Section 5',
  s5_title:      'Team Workload Distribution',
  ai_analysis:   'AI Generated Analysis',
  ai_offline:    'Narrative not available. AI service is offline.',
  insights:      'Key Insights and Action Items',
  s2_top:        'Tasks ranked by AI score. Showing top',
  s2_of:         'of',
  s2_scored:     'scored tasks.',
  th_rank:       '#',
  th_task:       'Task Title',
  th_type:       'Type',
  th_moscow:     'MoSCoW',
  th_rice:       'RICE',
  th_score:      'Final Score',
  th_status:     'Status',
  kpi_subtasks:  'Total Subtasks',
  kpi_todo:      'To Do',
  kpi_progress:  'In Progress',
  kpi_done:      'Done',
  kpi_complete:  'Completion',
  th_task_s:     'Task',
  th_subtask:    'Subtask',
  th_assignee:   'Assignee',
  th_complexity: 'Complexity',
  th_est:        'Est. Hours',
  kpi_sla:       'SLA Compliance',
  kpi_on_track:  'On Track',
  kpi_at_risk:   'At Risk',
  kpi_overdue:   'Overdue',
  kpi_completed: 'Completed',
  th_due:        'Due Date',
  th_sla:        'SLA Status',
  th_progress:   'Progress',
  s5_sub:        'team members. Capacity baseline: ~40h per sprint.',
  th_member:     'Member',
  th_role:       'Role',
  th_load:       'Load Level',
  th_total_act:  'Total Active',
  load_avail:    'Available',
  load_light:    'Light',
  load_moderate: 'Moderate',
  load_heavy:    'Heavy',
};

// ── Per-report translation hook (independent from global language) ───────────
function useReportTx(lang) {
  const [tx, setTx] = useState(REPORT_STRINGS);

  useEffect(() => {
    if (lang === 'en') { setTx(REPORT_STRINGS); return; }
    const cacheKey = `priorit_report_tx_${lang}`;
    try {
      const cached = JSON.parse(localStorage.getItem(cacheKey) || '{}');
      if (Object.keys(cached).length >= Object.keys(REPORT_STRINGS).length) {
        setTx(cached);
        return;
      }
    } catch {}
    translateBatch(Object.values(REPORT_STRINGS), lang).then(results => {
      const translated = {};
      Object.keys(REPORT_STRINGS).forEach((k, i) => {
        translated[k] = results[i] || REPORT_STRINGS[k];
      });
      setTx(translated);
      try { localStorage.setItem(`priorit_report_tx_${lang}`, JSON.stringify(translated)); } catch {}
    });
  }, [lang]);

  return tx;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

const MOSCOW_COLORS = {
  MUST:   { bg: '#FEF2F2', color: '#DC2626' },
  SHOULD: { bg: '#FFF7ED', color: '#D97706' },
  COULD:  { bg: '#EFF6FF', color: '#2563EB' },
  WONT:   { bg: '#F3F4F6', color: '#6B7280' },
};
const SLA_COLORS = {
  ON_TRACK:  '#16A34A',
  AT_RISK:   '#D97706',
  OVERDUE:   '#DC2626',
  COMPLETED: '#2563EB',
  NO_SLA:    '#9CA3AF',
};
function getLoadLabel(h, tx) {
  if (h === 0)  return tx.load_avail   || 'Available';
  if (h < 20)   return tx.load_light   || 'Light';
  if (h < 35)   return tx.load_moderate || 'Moderate';
  return              tx.load_heavy    || 'Heavy';
}
const LOAD_COLORS = (h) => h === 0 ? '#16A34A' : h < 20 ? '#2563EB' : h < 35 ? '#D97706' : '#DC2626';

function fmt(d) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

const today = new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });

// ── Print-safe styles ─────────────────────────────────────────────────────────

const PRINT_CSS = `
  @page { size: A4 portrait; margin: 0; }
  @media print {
    html, body { margin: 0 !important; padding: 0 !important; }
    .no-print { display: none !important; }
    .report-page {
      width: 210mm !important;
      min-height: 297mm !important;
      page-break-after: always !important;
      box-shadow: none !important;
      margin: 0 !important;
    }
    * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
  }
`;

// ── Sub-components ────────────────────────────────────────────────────────────

function PageHeader({ section, title, pageNum, tx }) {
  return (
    <div style={{ marginBottom: '1.5rem' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.6rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <div style={{ width: '4px', height: '28px', backgroundColor: '#CC2027', borderRadius: '9999px' }} />
          <div>
            <p style={{ fontSize: '0.62rem', fontWeight: '700', color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.1em' }}>{section}</p>
            <h2 style={{ fontSize: '1.25rem', fontWeight: '800', color: '#1A1A2E', margin: 0 }}>{title}</h2>
          </div>
        </div>
        <span style={{ fontSize: '0.65rem', color: '#9CA3AF' }}>{tx.page_label || 'Page'} {pageNum}</span>
      </div>
      <div style={{ height: '1px', backgroundColor: '#E5E7EB' }} />
    </div>
  );
}

function PageFooter({ tx }) {
  return (
    <div style={{
      position: 'absolute', bottom: '1.5rem', left: '2rem', right: '2rem',
      display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      borderTop: '1px solid #E5E7EB', paddingTop: '0.75rem',
    }}>
      <span style={{ fontSize: '0.6rem', color: '#9CA3AF' }}>{tx.footer || 'Attijari Bank IT Department — PriorIT Report — CONFIDENTIAL'}</span>
      <span style={{ fontSize: '0.6rem', color: '#9CA3AF' }}>{today}</span>
    </div>
  );
}

function Page({ children, minHeight = '297mm' }) {
  return (
    <div className="report-page" style={{
      width: '210mm', minHeight,
      backgroundColor: 'white',
      margin: '0 auto 2rem auto',
      boxShadow: '0 4px 24px rgba(0,0,0,0.12)',
      position: 'relative',
      padding: '2rem',
      boxSizing: 'border-box',
    }}>
      {children}
    </div>
  );
}

function KpiCard({ value, label, sub, color = '#CC2027' }) {
  return (
    <div style={{
      flex: 1, backgroundColor: 'white', border: '1px solid #F0F0F0',
      borderTop: `3px solid ${color}`, borderRadius: '0.5rem',
      padding: '1rem', textAlign: 'center',
    }}>
      <p style={{ fontSize: '2rem', fontWeight: '800', color, lineHeight: 1 }}>{value}</p>
      <p style={{ fontSize: '0.72rem', fontWeight: '700', color: '#374151', marginTop: '0.25rem' }}>{label}</p>
      {sub && <p style={{ fontSize: '0.62rem', color: '#9CA3AF', marginTop: '0.1rem' }}>{sub}</p>}
    </div>
  );
}

function Table({ headers, rows, colWidths }) {
  return (
    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.72rem' }}>
      <thead>
        <tr style={{ backgroundColor: '#1A1A2E' }}>
          {headers.map((h, i) => (
            <th key={i} style={{
              padding: '0.5rem 0.6rem', color: 'white', textAlign: 'left',
              fontWeight: '700', fontSize: '0.65rem', letterSpacing: '0.05em',
              textTransform: 'uppercase',
              width: colWidths?.[i],
            }}>{h}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, ri) => (
          <tr key={ri} style={{ backgroundColor: ri % 2 === 0 ? 'white' : '#F9FAFB' }}>
            {row.map((cell, ci) => (
              <td key={ci} style={{ padding: '0.45rem 0.6rem', color: '#374151', borderBottom: '1px solid #F0F0F0', verticalAlign: 'middle' }}>
                {cell}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function AiBadge({ tx }) {
  return (
    <span style={{
      display: 'inline-flex', alignItems: 'center', gap: '0.25rem',
      fontSize: '0.6rem', fontWeight: '700', padding: '0.15rem 0.5rem',
      borderRadius: '9999px', backgroundColor: '#F5F3FF', color: '#7C3AED',
      border: '1px solid #DDD6FE', marginLeft: '0.5rem',
      textTransform: 'uppercase', letterSpacing: '0.04em',
    }}>✦ {tx.ai_badge || 'AI Generated'}</span>
  );
}

function MoscowBadge({ label }) {
  const s = MOSCOW_COLORS[label] || { bg: '#F3F4F6', color: '#6B7280' };
  return (
    <span style={{
      padding: '0.15rem 0.45rem', borderRadius: '9999px',
      fontSize: '0.62rem', fontWeight: '700',
      backgroundColor: s.bg, color: s.color,
    }}>{label || '—'}</span>
  );
}

function StatusDot({ status, text }) {
  const color = SLA_COLORS[status] || '#9CA3AF';
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.3rem' }}>
      <span style={{ width: 7, height: 7, borderRadius: '50%', backgroundColor: color, display: 'inline-block' }} />
      <span style={{ color, fontWeight: '700', fontSize: '0.68rem' }}>{text}</span>
    </span>
  );
}

// ── Report pages ──────────────────────────────────────────────────────────────

function CoverPage({ user, tasks, subtasks, slaItems, members, tx }) {
  const scoredTasks  = tasks.filter(t => t.finalScore != null).length;
  const sprintDone   = subtasks.filter(s => s.status === 'DONE').length;
  const sprintPct    = subtasks.length > 0 ? Math.round((sprintDone / subtasks.length) * 100) : 0;
  const slaCompliant = slaItems.filter(i => i.slaStatus === 'ON_TRACK' || i.slaStatus === 'COMPLETED').length;
  const slaCompPct   = slaItems.length > 0 ? Math.round((slaCompliant / slaItems.length) * 100) : 0;

  return (
    <div className="report-page" style={{
      width: '210mm', minHeight: '297mm', margin: '0 auto 2rem auto',
      boxShadow: '0 4px 24px rgba(0,0,0,0.12)',
      backgroundColor: '#1A1A2E', position: 'relative',
      display: 'flex', flexDirection: 'column',
      boxSizing: 'border-box',
    }}>
      {/* Top brand strip */}
      <div style={{ padding: '2.5rem 2.5rem 0' }}>
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', marginBottom: '3rem' }}>
          <div style={{
            width: '28px', height: '28px', backgroundColor: '#CC2027',
            borderRadius: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <span style={{ color: 'white', fontSize: '13px', fontWeight: '800' }}>P</span>
          </div>
          <span style={{ color: 'white', fontSize: '1.1rem', fontWeight: '700' }}>
            Prior<span style={{ color: '#CC2027' }}>IT</span>
          </span>
          <span style={{ color: '#4B5563', fontSize: '0.7rem', marginLeft: '0.5rem' }}>by Attijari Bank</span>
        </div>

        {/* Title */}
        <div style={{ marginBottom: '2.5rem' }}>
          <div style={{ width: '48px', height: '4px', backgroundColor: '#CC2027', borderRadius: '9999px', marginBottom: '1.5rem' }} />
          <h1 style={{ fontSize: '2.25rem', fontWeight: '900', color: 'white', lineHeight: 1.15, marginBottom: '0.75rem' }}>
            {tx.it_dept || 'IT Department'}<br />{tx.s2_title ? '' : 'Management Report'}
          </h1>
          <p style={{ fontSize: '0.9rem', color: '#9CA3AF', fontWeight: '400', marginBottom: '0.5rem' }}>
            {tx.bank || 'IT Department · Attijari Bank Tunisia'}
          </p>
          <p style={{ fontSize: '0.8rem', color: '#6B7280' }}>
            {today} · {tx.gen_by || 'Generated by'} {user?.name ?? 'IT Manager'}
          </p>
        </div>

        {/* Divider */}
        <div style={{ height: '1px', backgroundColor: 'rgba(255,255,255,0.08)', marginBottom: '2.5rem' }} />

        {/* KPI summary */}
        <div style={{ display: 'flex', gap: '0.875rem', marginBottom: '3rem' }}>
          {[
            { value: tasks.length, label: tx.c_tasks || 'Total Tasks', color: '#CC2027' },
            { value: scoredTasks,  label: tx.c_ai    || 'AI Scored',   color: '#7C3AED' },
            { value: `${sprintPct}%`, label: tx.c_sprint || 'Sprint Progress', color: '#16A34A' },
            { value: `${slaCompPct}%`, label: tx.c_sla  || 'SLA Compliance',  color: '#2563EB' },
            { value: members.length, label: tx.c_team  || 'Team Members',    color: '#D97706' },
          ].map(k => (
            <div key={k.label} style={{
              flex: 1, backgroundColor: 'rgba(255,255,255,0.04)',
              border: '1px solid rgba(255,255,255,0.06)',
              borderTop: `3px solid ${k.color}`,
              borderRadius: '0.5rem', padding: '1rem 0.75rem', textAlign: 'center',
            }}>
              <p style={{ fontSize: '1.6rem', fontWeight: '900', color: k.color, lineHeight: 1 }}>{k.value}</p>
              <p style={{ fontSize: '0.6rem', color: '#9CA3AF', fontWeight: '600', marginTop: '0.25rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>{k.label}</p>
            </div>
          ))}
        </div>

        <div style={{ height: '1px', backgroundColor: 'rgba(255,255,255,0.06)' }} />
      </div>

      {/* Bottom strip */}
      <div style={{ marginTop: 'auto', padding: '1.5rem 2.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <span style={{ fontSize: '0.6rem', color: '#4B5563', textTransform: 'uppercase', letterSpacing: '0.1em' }}>{tx.confidential || 'Confidential — Internal Use Only'}</span>
        <span style={{ fontSize: '0.6rem', color: '#4B5563' }}>{tx.version || 'PriorIT v1.0'}</span>
      </div>
    </div>
  );
}

function ExecutiveSummaryPage({ narrative, tx }) {
  return (
    <Page>
      <PageHeader section={tx.s1 || 'Section 1'} title={tx.s1_title || 'Executive Summary'} pageNum={2} tx={tx} />

      <div style={{ marginBottom: '2rem' }}>
        <p style={{ fontSize: '0.7rem', color: '#7C3AED', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
          <span>{tx.ai_analysis || 'AI-Generated Analysis'}</span><AiBadge tx={tx} />
        </p>
        {narrative?.executiveSummary ? (
          <div style={{ fontSize: '0.83rem', color: '#374151', lineHeight: '1.8' }}>
            {narrative.executiveSummary.split('\n').filter(Boolean).map((p, i) => (
              <p key={i} style={{ marginBottom: '0.875rem' }}>{p}</p>
            ))}
          </div>
        ) : (
          <p style={{ fontSize: '0.83rem', color: '#9CA3AF', fontStyle: 'italic' }}>{tx.ai_offline || 'Narrative unavailable — AI service offline.'}</p>
        )}
      </div>

      {narrative?.keyInsights?.length > 0 && (
        <div style={{
          backgroundColor: '#F9FAFB', borderRadius: '0.625rem',
          border: '1px solid #E5E7EB', padding: '1.25rem',
        }}>
          <p style={{ fontSize: '0.72rem', fontWeight: '800', color: '#1A1A2E', textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: '0.75rem' }}>
            {tx.insights || 'Key Insights & Action Items'}
          </p>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
            {narrative.keyInsights.map((insight, i) => (
              <li key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '0.65rem' }}>
                <span style={{
                  minWidth: '20px', height: '20px', backgroundColor: '#CC2027',
                  borderRadius: '50%', display: 'flex', alignItems: 'center',
                  justifyContent: 'center', flexShrink: 0, marginTop: '0.05rem',
                }}>
                  <span style={{ color: 'white', fontSize: '0.6rem', fontWeight: '800' }}>{i + 1}</span>
                </span>
                <span style={{ fontSize: '0.8rem', color: '#374151', lineHeight: '1.6' }}>{insight}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <PageFooter tx={tx} />
    </Page>
  );
}

function TaskPriorityPage({ tasks, tx }) {
  const scored = tasks
    .filter(t => t.finalScore != null)
    .sort((a, b) => b.finalScore - a.finalScore)
    .slice(0, 18);

  return (
    <Page>
      <PageHeader section={tx.s2 || 'Section 2'} title={tx.s2_title || 'Task Priority Ranking'} pageNum={3} tx={tx} />
      <p style={{ fontSize: '0.75rem', color: '#9CA3AF', marginBottom: '1rem' }}>
        {tx.s2_top || 'Tasks ranked by final AI score (RICE × Kano × MoSCoW). Showing top'} {scored.length} {tx.s2_of || 'of'} {tasks.filter(t => t.finalScore != null).length} {tx.s2_scored || 'scored tasks.'}
      </p>
      <Table
        headers={[tx.th_rank || '#', tx.th_task || 'Task Title', tx.th_type || 'Type', tx.th_moscow || 'MoSCoW', tx.th_rice || 'RICE', tx.th_score || 'Final Score', tx.th_status || 'Status']}
        colWidths={['28px', undefined, '90px', '70px', '50px', '70px', '100px']}
        rows={scored.map((t, i) => [
          <span key="rank" style={{ fontWeight: '800', color: i < 3 ? '#CC2027' : '#9CA3AF' }}>{i + 1}</span>,
          <span key="title" style={{ fontWeight: '600', color: '#111827' }}>{t.title}</span>,
          <span key="type" style={{ fontSize: '0.65rem', color: '#6B7280' }}>{t.taskType ?? '—'}</span>,
          <MoscowBadge key="moscow" label={t.moscowLabel} />,
          <span key="rice" style={{ fontWeight: '600', color: '#374151' }}>{t.riceScore?.toFixed(1) ?? '—'}</span>,
          <span key="score" style={{ fontWeight: '800', color: '#CC2027' }}>{t.finalScore?.toFixed(1)}</span>,
          <span key="status" style={{ fontSize: '0.62rem', color: '#6B7280' }}>{t.status?.replace(/_/g, ' ') ?? '—'}</span>,
        ])}
      />
      <PageFooter tx={tx} />
    </Page>
  );
}

function SprintPage({ subtasks, narrative, tx }) {
  const todo = subtasks.filter(s => s.status === 'TODO').length;
  const inProg = subtasks.filter(s => s.status === 'IN_PROGRESS').length;
  const done = subtasks.filter(s => s.status === 'DONE').length;
  const pct = subtasks.length > 0 ? Math.round((done / subtasks.length) * 100) : 0;

  return (
    <Page>
      <PageHeader section={tx.s3 || 'Section 3'} title={tx.s3_title || 'Active Sprint Status'} pageNum={4} tx={tx} />

      {/* KPIs */}
      <div style={{ display: 'flex', gap: '0.75rem', marginBottom: '1.25rem' }}>
        {[
          { v: subtasks.length, l: tx.kpi_subtasks || 'Total Subtasks', c: '#1A1A2E' },
          { v: todo,            l: tx.kpi_todo     || 'To Do',          c: '#6B7280' },
          { v: inProg,          l: tx.kpi_progress || 'In Progress',    c: '#2563EB' },
          { v: done,            l: tx.kpi_done     || 'Done',           c: '#16A34A' },
          { v: `${pct}%`,       l: tx.kpi_complete || 'Completion',     c: '#CC2027' },
        ].map(k => <KpiCard key={k.l} value={k.v} label={k.l} color={k.c} />)}
      </div>

      {/* AI Commentary */}
      {narrative?.sprintCommentary && (
        <div style={{
          backgroundColor: '#F5F3FF', border: '1px solid #DDD6FE',
          borderRadius: '0.5rem', padding: '0.875rem 1rem', marginBottom: '1.25rem',
          display: 'flex', gap: '0.6rem',
        }}>
          <span style={{ color: '#7C3AED', fontSize: '0.9rem' }}>✦</span>
          <p style={{ fontSize: '0.775rem', color: '#4C1D95', lineHeight: '1.7', margin: 0 }}>
            {narrative.sprintCommentary}
          </p>
        </div>
      )}

      <Table
        headers={[tx.th_task_s || 'Task', tx.th_subtask || 'Subtask', tx.th_assignee || 'Assignee', tx.th_status || 'Status', tx.th_complexity || 'Complexity', tx.th_est || 'Est. Hours']}
        colWidths={['22%', undefined, '15%', '90px', '70px', '70px']}
        rows={subtasks.slice(0, 20).map(s => [
          <span key="task" style={{ fontSize: '0.65rem', color: '#9CA3AF' }}>{s.taskTitle}</span>,
          <span key="sub" style={{ fontWeight: '600', color: '#111827' }}>{s.title}</span>,
          <span key="assignee" style={{ color: '#6B7280' }}>{s.submittedByName?.split(' ')[0] ?? '—'}</span>,
          <StatusDot key="status" status={s.status === 'DONE' ? 'ON_TRACK' : s.status === 'IN_PROGRESS' ? 'AT_RISK' : 'NO_SLA'}
            text={s.status?.replace('_', ' ') ?? '—'} />,
          <span key="cx" style={{ fontSize: '0.65rem', color: '#6B7280' }}>{s.complexity ?? '—'}</span>,
          <span key="h" style={{ fontWeight: '600', color: '#374151' }}>{s.estimatedHours != null ? `${s.estimatedHours}h` : '—'}</span>,
        ])}
      />
      <PageFooter tx={tx} />
    </Page>
  );
}

function SlaPageSection({ slaItems, narrative, tx }) {
  const onTrack   = slaItems.filter(i => i.slaStatus === 'ON_TRACK').length;
  const atRisk    = slaItems.filter(i => i.slaStatus === 'AT_RISK').length;
  const overdue   = slaItems.filter(i => i.slaStatus === 'OVERDUE').length;
  const completed = slaItems.filter(i => i.slaStatus === 'COMPLETED').length;
  const compPct   = slaItems.length > 0 ? Math.round(((onTrack + completed) / slaItems.length) * 100) : 0;

  return (
    <Page>
      <PageHeader section={tx.s4 || 'Section 4'} title={tx.s4_title || 'SLA & Delivery Compliance'} pageNum={5} tx={tx} />

      <div style={{ display: 'flex', gap: '0.75rem', marginBottom: '1.25rem' }}>
        {[
          { v: `${compPct}%`, l: tx.kpi_sla       || 'SLA Compliance', c: '#CC2027' },
          { v: onTrack,       l: tx.kpi_on_track   || 'On Track',       c: '#16A34A' },
          { v: atRisk,        l: tx.kpi_at_risk    || 'At Risk',        c: '#D97706' },
          { v: overdue,       l: tx.kpi_overdue    || 'Overdue',        c: '#DC2626' },
          { v: completed,     l: tx.kpi_completed  || 'Completed',      c: '#2563EB' },
        ].map(k => <KpiCard key={k.l} value={k.v} label={k.l} color={k.c} />)}
      </div>

      {narrative?.slaAssessment && (
        <div style={{
          backgroundColor: overdue > 0 ? '#FEF2F2' : '#F0FDF4',
          border: `1px solid ${overdue > 0 ? '#FECACA' : '#BBF7D0'}`,
          borderRadius: '0.5rem', padding: '0.875rem 1rem', marginBottom: '1.25rem',
          display: 'flex', gap: '0.6rem',
        }}>
          <span style={{ color: overdue > 0 ? '#DC2626' : '#16A34A', fontSize: '0.9rem' }}>✦</span>
          <p style={{ fontSize: '0.775rem', color: '#374151', lineHeight: '1.7', margin: 0 }}>
            {narrative.slaAssessment}
          </p>
        </div>
      )}

      <Table
        headers={[tx.th_task_s || 'Task', tx.th_type || 'Type', tx.th_assignee || 'Assignee', tx.th_due || 'Due Date', tx.th_sla || 'SLA Status', tx.th_progress || 'Progress']}
        colWidths={[undefined, '90px', '12%', '90px', '80px', '70px']}
        rows={slaItems.slice(0, 18).map(i => [
          <span key="task" style={{ fontWeight: '600', color: '#111827' }}>{i.taskTitle}</span>,
          <span key="type" style={{ fontSize: '0.65rem', color: '#6B7280' }}>{i.taskType ?? '—'}</span>,
          <span key="ass"  style={{ color: '#6B7280' }}>{i.assigneeName?.split(' ')[0] ?? '—'}</span>,
          <span key="due"  style={{ color: '#374151' }}>{fmt(i.dueDate)}</span>,
          <StatusDot key="sla" status={i.slaStatus} text={i.slaStatus?.replace('_', ' ') ?? '—'} />,
          <div key="prog" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            <div style={{ width: '50px', height: '5px', backgroundColor: '#E5E7EB', borderRadius: '9999px', overflow: 'hidden' }}>
              <div style={{ height: '100%', width: `${i.progressPercent ?? 0}%`, backgroundColor: '#16A34A', borderRadius: '9999px' }} />
            </div>
            <span style={{ fontSize: '0.65rem', fontWeight: '700', color: '#374151' }}>{i.progressPercent ?? 0}%</span>
          </div>,
        ])}
      />
      <PageFooter tx={tx} />
    </Page>
  );
}

function WorkloadPageSection({ members, tx }) {
  return (
    <Page>
      <PageHeader section={tx.s5 || 'Section 5'} title={tx.s5_title || 'Team Workload Distribution'} pageNum={6} tx={tx} />
      <p style={{ fontSize: '0.75rem', color: '#9CA3AF', marginBottom: '1rem' }}>
        Active sprint hours across {members.length} {tx.s5_sub || 'team members. Capacity baseline: ~40h per sprint.'}
      </p>
      <Table
        headers={[tx.th_member || 'Member', tx.th_role || 'Role', tx.th_est || 'Est. Hours', tx.th_load || 'Load Level', tx.kpi_todo || 'To Do', tx.kpi_progress || 'In Progress', tx.kpi_done || 'Done', tx.th_total_act || 'Total Active']}
        colWidths={[undefined, '100px', '75px', '80px', '50px', '80px', '50px', '70px']}
        rows={[...members].sort((a, b) => b.totalEstimatedHours - a.totalEstimatedHours).map(m => {
          const pct = Math.min((m.totalEstimatedHours / 40) * 100, 100);
          const lc  = LOAD_COLORS(m.totalEstimatedHours);
          return [
            <span key="name" style={{ fontWeight: '700', color: '#111827' }}>{m.name}</span>,
            <span key="role" style={{ fontSize: '0.65rem', color: '#6B7280' }}>{m.role?.replace('_', ' ')}</span>,
            <div key="bar" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <div style={{ width: '45px', height: '5px', backgroundColor: '#E5E7EB', borderRadius: '9999px', overflow: 'hidden' }}>
                <div style={{ height: '100%', width: `${pct}%`, backgroundColor: lc, borderRadius: '9999px' }} />
              </div>
              <span style={{ fontWeight: '700', color: lc, fontSize: '0.7rem' }}>{m.totalEstimatedHours}h</span>
            </div>,
            <span key="load" style={{ fontWeight: '700', color: lc, fontSize: '0.68rem' }}>{getLoadLabel(m.totalEstimatedHours, tx)}</span>,
            <span key="todo" style={{ color: '#6B7280', fontWeight: '600' }}>{m.todoCount}</span>,
            <span key="inp"  style={{ color: '#2563EB', fontWeight: '600' }}>{m.inProgressCount}</span>,
            <span key="done" style={{ color: '#16A34A', fontWeight: '600' }}>{m.doneCount}</span>,
            <span key="tot"  style={{ fontWeight: '700', color: '#1A1A2E' }}>{m.todoCount + m.inProgressCount + m.doneCount}</span>,
          ];
        })}
      />
      <PageFooter tx={tx} />
    </Page>
  );
}

// ── Language picker button ────────────────────────────────────────────────────

const LANG_OPTIONS = [
  { code: 'en', label: 'EN' },
  { code: 'fr', label: 'FR' },
  { code: 'ar', label: 'AR' },
];

// ── Main page ─────────────────────────────────────────────────────────────────

export default function ReportPage() {
  const { theme } = useTheme();
  const navigate  = useNavigate();
  const { user }  = useAuthStore();
  const { language: globalLang } = useLanguage();

  // Report language is independent from the global UI language
  const [reportLang, setReportLang] = useState(globalLang);
  const [translating, setTranslating] = useState(false);
  const tx = useReportTx(reportLang);

  const [loading, setLoading]     = useState(true);
  const [aiLoading, setAiLoading] = useState(false);
  const [error, setError]         = useState('');
  const [tasks, setTasks]         = useState([]);
  const [subtasks, setSubtasks]   = useState([]);
  const [slaItems, setSlaItems]   = useState([]);
  const [members, setMembers]     = useState([]);
  const [narrative, setNarrative] = useState(null);

  // Watch for translation completion
  useEffect(() => {
    if (reportLang !== 'en') setTranslating(true);
    const timer = setTimeout(() => setTranslating(false), 3000);
    return () => clearTimeout(timer);
  }, [reportLang]);

  useEffect(() => {
    const fetchAll = async () => {
      try {
        const [allTasks, boardData, slaData, workloadData] = await Promise.all([
          taskService.getAllTasks(),
          sprintService.getBoard(),
          slaService.getAll(),
          sprintService.getWorkload(),
        ]);
        const t = allTasks || [];
        const s = boardData?.subtasks || [];
        const sl = slaData || [];
        const m = workloadData?.members || [];

        setTasks(t);
        setSubtasks(s);
        setSlaItems(sl);
        setMembers(m);

        // Build stats for AI
        const scoredTasks   = t.filter(x => x.finalScore != null);
        const approvedTasks = t.filter(x => x.status === 'APPROVED');
        const topTasks      = scoredTasks.sort((a, b) => b.finalScore - a.finalScore)
                              .slice(0, 5)
                              .map(x => ({ title: x.title, score: x.finalScore?.toFixed(1), moscow: x.moscowLabel ?? 'N/A' }));
        const sprintDone    = s.filter(x => x.status === 'DONE').length;
        const slaOk         = sl.filter(x => x.slaStatus === 'ON_TRACK' || x.slaStatus === 'COMPLETED').length;

        const stats = {
          totalTasks: t.length, scoredTasks: scoredTasks.length, approvedTasks: approvedTasks.length,
          topTasks,
          sprintTotal: s.length, sprintTodo: s.filter(x => x.status === 'TODO').length,
          sprintInProgress: s.filter(x => x.status === 'IN_PROGRESS').length, sprintDone,
          sprintPct: s.length > 0 ? Math.round((sprintDone / s.length) * 100) : 0,
          slaTotal: sl.length, slaOnTrack: sl.filter(x => x.slaStatus === 'ON_TRACK').length,
          slaAtRisk: sl.filter(x => x.slaStatus === 'AT_RISK').length,
          slaOverdue: sl.filter(x => x.slaStatus === 'OVERDUE').length,
          slaCompliancePct: sl.length > 0 ? Math.round((slaOk / sl.length) * 100) : 0,
          teamTotal: m.length,
          teamAvailable: m.filter(x => x.totalEstimatedHours === 0).length,
          teamModerate: m.filter(x => x.totalEstimatedHours >= 20 && x.totalEstimatedHours < 35).length,
          teamHeavy: m.filter(x => x.totalEstimatedHours >= 35).length,
          teamTotalHours: m.reduce((sum, x) => sum + x.totalEstimatedHours, 0).toFixed(0),
        };

        setAiLoading(true);
        try {
          const aiRes = await api.post('/api/report/summary', stats);
          setNarrative(aiRes.data);
        } catch { /* use null narrative — will show fallback text */ }
        setAiLoading(false);

      } catch (e) {
        setError('Failed to load report data. Make sure the backend is running.');
      } finally {
        setLoading(false);
      }
    };
    fetchAll();
  }, []);

  if (loading) {
    return (
      <div style={{
        marginLeft: '240px', minHeight: '100vh', display: 'flex',
        flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
        backgroundColor: theme.pageBg, gap: '1rem',
      }}>
        <style>{PRINT_CSS}</style>
        <RefreshCw size={32} color="#CC2027" style={{ animation: 'spin 1s linear infinite' }} />
        <p style={{ color: theme.textSub, fontWeight: '600', fontSize: '0.875rem' }}>Loading report data…</p>
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      </div>
    );
  }

  if (error) {
    return (
      <div style={{ marginLeft: '240px', minHeight: '100vh', padding: '3rem', backgroundColor: theme.pageBg }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', backgroundColor: '#FEF2F2', border: '1px solid #FECACA', borderRadius: '0.75rem', padding: '1rem 1.25rem' }}>
          <AlertCircle size={18} color="#DC2626" />
          <p style={{ color: '#DC2626', fontSize: '0.875rem' }}>{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div style={{ marginLeft: '240px', backgroundColor: theme.tagBg, minHeight: '100vh', paddingBottom: '3rem' }}>
      <style>{PRINT_CSS}</style>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>

      {/* Controls bar — hidden when printing */}
      <div className="no-print" style={{
        position: 'sticky', top: 0, zIndex: 50,
        backgroundColor: '#1A1A2E',
        padding: '0.875rem 2rem',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <button onClick={() => navigate(-1)} style={{
            display: 'flex', alignItems: 'center', gap: '0.4rem',
            padding: '0.4rem 0.875rem', borderRadius: '0.4rem',
            border: '1px solid rgba(255,255,255,0.15)', backgroundColor: 'transparent',
            color: '#9CA3AF', fontSize: '0.8rem', cursor: 'pointer',
          }}>
            <ArrowLeft size={14} /> Back
          </button>
          <span style={{ color: 'white', fontWeight: '700', fontSize: '0.875rem' }}>
            IT Management Report
          </span>
          {aiLoading && (
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', fontSize: '0.72rem', color: '#A78BFA' }}>
              <RefreshCw size={11} style={{ animation: 'spin 1s linear infinite' }} />
              AI generating narrative…
            </span>
          )}
          {translating && (
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', fontSize: '0.72rem', color: '#6EE7B7' }}>
              <RefreshCw size={11} style={{ animation: 'spin 1s linear infinite' }} />
              Translating report…
            </span>
          )}
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          {/* Report language picker */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span style={{ color: '#6B7280', fontSize: '0.72rem' }}>Report language:</span>
            <div style={{ display: 'flex', backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: '0.4rem', padding: '0.15rem', gap: '0.15rem' }}>
              {LANG_OPTIONS.map(({ code, label }) => (
                <button
                  key={code}
                  onClick={() => setReportLang(code)}
                  style={{
                    padding: '0.3rem 0.625rem', borderRadius: '0.3rem', border: 'none',
                    cursor: 'pointer', fontSize: '0.72rem', fontWeight: '700',
                    backgroundColor: reportLang === code ? '#CC2027' : 'transparent',
                    color: reportLang === code ? 'white' : '#9CA3AF',
                    transition: 'all 0.15s',
                  }}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={() => window.print()}
            style={{
              display: 'flex', alignItems: 'center', gap: '0.5rem',
              padding: '0.55rem 1.25rem', borderRadius: '0.5rem',
              border: 'none', backgroundColor: '#CC2027',
              color: 'white', fontSize: '0.825rem', fontWeight: '700',
              cursor: 'pointer',
            }}
          >
            <Printer size={15} /> Print / Save as PDF
          </button>
        </div>
      </div>

      {/* Tip bar */}
      <div className="no-print" style={{
        backgroundColor: '#F5F3FF', borderBottom: '1px solid #DDD6FE',
        padding: '0.6rem 2rem', fontSize: '0.72rem', color: '#6D28D9',
        display: 'flex', alignItems: 'center', gap: '0.5rem',
      }}>
        <span>✦</span>
        <span>
          <strong>Print tip:</strong> In the print dialog, select <strong>A4</strong> paper, set margins to <strong>None</strong>, and enable <strong>Background graphics</strong> to preserve colors.
        </span>
      </div>

      {/* Report pages */}
      <div style={{ padding: '2.5rem 2rem 0' }}>
        <CoverPage user={user} tasks={tasks} subtasks={subtasks} slaItems={slaItems} members={members} tx={tx} />
        <ExecutiveSummaryPage narrative={narrative} tx={tx} />
        <TaskPriorityPage tasks={tasks} tx={tx} />
        <SprintPage subtasks={subtasks} narrative={narrative} tx={tx} />
        <SlaPageSection slaItems={slaItems} narrative={narrative} tx={tx} />
        <WorkloadPageSection members={members} tx={tx} />
      </div>
    </div>
  );
}
